version: "3"

services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    command: yarn dev
    depends_on:
      - mongodb
    volumes:
      - .:/home/app/node_docker
  mongodb:
    image: mongo:3.2.5